openapi: 3.0.3
info:
  version: 0.1.0
  title: TesfaFund API
  description: API specification for the TesfaFund platform.
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
servers:
  - url: http://localhost:4000
tags:
  - name: Supervisor
    description: Supervisor management and authentication.
  - name: Recipient
    description: Recipient management and authentication.
  - name: Campaigns
    description: Campaign management.
  - name: Donations
    description: Donation management.
  - name: Campaign Requests
    description: Campaign workflows requiring supervisor approval.
paths:
  /campaigns:
    get:
      tags:
        - Campaigns
      summary: Browse live campaigns
      description: Retrieves a list of live campaigns, with optional filtering and pagination.
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: Page number for pagination.
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of items per page.
        - name: status
          in: query
          schema:
            type: string
            enum: [live, pending, completed, rejected]
          description: Filter by campaign status.
        - name: category
          in: query
          schema:
            type: string
          description: Filter by campaign category.
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campaign'
        '400':
          description: Bad request
        '500':
          description: Internal server error
    post:
      tags:
        - Campaigns
      summary: Apply for campaign creation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Campaign'
      responses:
        '201':
          description: Campaign creation request created.
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /campaigns/{campaignId}:
    get:
      tags:
        - Campaigns
      summary: Get campaign details
      description: Retrieves the details of a specific live campaign.
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to retrieve.
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campaign'
        '404':
          description: Campaign not found or not live.
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /campaigns/{campaignId}/donate:
    post:
      tags:
        - Donations
      summary: Donate to a campaign
      description: Creates a new donation for a specific campaign.
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to donate to.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Donation'
      responses:
        '201':
          description: Donation created successfully
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaigns:
    get:
      tags:
        - Campaigns
      summary: Get recipient's campaigns
      description: Retrieves a list of campaigns owned by the authenticated recipient.
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: Page number for pagination.
        - name: limit
          in: query
          schema:
            type: integer
          description: Maximum number of items per page.
        - name: status
          in: query
          schema:
            type: string
            enum: [live, pending, completed, rejected]
          description: Filter by campaign status.
        - name: title
          in: query
          schema:
            type: string
          description: Filter by campaign title (substring match).
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campaign'
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaigns/{campaignId}:
    get:
      tags:
        - Campaigns
      summary: Get recipient's campaign details
      description: Retrieves the details of a specific campaign owned by the authenticated recipient.
      security:
        - bearerAuth: []
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to retrieve.
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campaign'
        '401':
          description: Unauthorized
        '404':
          description: Campaign Not found.
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaigns/{campaignId}/requests/extend-end:
    post:
      tags:
        - Campaign Requests
      summary: Request campaign end extension
      security:
        - bearerAuth: []
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to request an extension for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignEndExtensionRequest'
      responses:
        '201':
          description: Request created successfully
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaigns/{campaignId}/requests/change-status:
    post:
      tags:
        - Campaign Requests
      summary: Request campaign status change
      security:
        - bearerAuth: []
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to request a status change for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignStatusChangeRequest'
      responses:
        '201':
          description: Request created successfully
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaigns/{campaignId}/requests/adjust-goal:
    post:
      tags:
        - Campaign Requests
      summary: Request campaign goal adjustment
      security:
        - bearerAuth: []
      parameters:
        - name: campaignId
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the campaign to request a goal adjustment for.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CampaignGoalAdjustmentRequest'
      responses:
        '201':
          description: Request created successfully
        '401':
          description: Unauthorized
        '400':
          description: Bad request
        '500':
          description: Internal server error
  /recipient/campaign-adjustment-requests:
    get:
      tags:
        - Campaign Requests
      summary: Get recipient's campaign adjustment requests
      security:
        - bearerAuth: []
      parameters:
        - name: page
          in: query
          schema:
            type: integer
          description: Page number for pagination.