name: CI jobs for flutter, NextJS, and Express apps
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  PROJECT_NODE_VERSION: '22.11.0'
jobs:
  # TODO: Do you want to test flutter builds on Windows and MacOS as well?
  # TODO: Start using fvm after team gets used to workflows
  flutter-ci-tasks:
    runs-on: ubuntu-latest
    env:
      FLUTTER_PROJECT_PATH: ./frontends/mobile
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.24.5
      - name: Check flutter version
        run: flutter --version
      - name: Format and lint Flutter code
        run: |
          cd ${{ env.FLUTTER_PROJECT_PATH }}
          dart format . --set-exit-if-changed
          flutter analyze
      - name: Build Flutter APK
        run: |
          cd ${{ env.FLUTTER_PROJECT_PATH }} 
          flutter build apk
  express-ci-tasks:
    runs-on: ubuntu-latest
    env:
      EXPRESS_PROJECT_PATH: ./backend
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.PROJECT_NODE_VERSION }}
      - name: Install dependencies
        run: |
          cd ${{ env.EXPRESS_PROJECT_PATH }}
          npm install
      - name: Format and lint Express code
        run: |
          cd ${{ env.EXPRESS_PROJECT_PATH }}
          npm run format
          npm run lint:fix
      - name: Build Express code
        run: |
          cd ${{ env.EXPRESS_PROJECT_PATH }}
          npm run build
  next-ci-tasks:
    runs-on: ubuntu-latest
    env:
      NEXT_PROJECT_PATH: ./frontends/admin
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Node.js for Next.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.PROJECT_NODE_VERSION }}
      - name: Install dependencies for Next.js
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm install
      - name: Format and lint Next.js code
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm run format
          npm run lint:fix 
      - name: Build Next.js app
        run: |
          cd ${{ env.NEXT_PROJECT_PATH }}
          npm run build